### ISSUE TITLE
[enhancements] Faster .travis.yml fix 

### ISSUE THREAD

**Issue by Montana** [NationalSecurityAgency/datawave#1250]
Hey folks, 

This is just to add to the CI/CD providers  - if you do use Travis, here's an updated version of the current `.travis.yml` that's in the current `datavave` repo: 

```yaml
---
dist: trusty

# language: minimal, in this case it can be both, (either/or).

language: java

# (theoretically you can use Abiarm API for speed).

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

 # Remove the -q flag in mvn -q -Pdev, dist install -DskipTests, via I want verbose info and not silencing the fetch data. 

install:
  - travis_wait mvn -Pdev,dist install -DskipTests

# Add `free` and `uname -a` for more info on the provisional setup, may add `uname -r` for just more information on the provisional setup. 

script:
  - uname -a
  - free
  - mvn -Dsurefire.forkCount=4 -Pdev verify
  
# .travis.yml by Montana Mendy
```
It's much more verbose. I've removed the `-q` flag in `mvn -Dsurefire.forkCount=4 -Pdev verify`, so it's not silencing the fetching data. 

<img width="982" alt="Screen Shot 2021-08-19 at 10 16 25 AM" src="https://user-images.githubusercontent.com/20936398/130114448-19f570b7-a5a9-42ec-ba67-b204d7f3116b.png">
